### ISSUE TITLE
Not correctly stripping parameters from sources

### ISSUE THREAD

**Issue by Schepp** [aFarkas/jMediaelement#1]
Today I built player where one had a video-file and where one was able to upload a video that then replaced that video-file - but bearing the exact same name. So I needed to suppress user-agent-caching of the file and appended a constantly changing "?nocache=xyz" to it. When doing this the video-player broke (at least it did under Firefox with the JWPlayer-fallback) and I found out why: In line 212 you add the "?" to the file-extension, which then cannot be resolved into any known mime-type (e.g. instead of "mp4" one gets "mp4?"). When changing the line from "var pos = (src.indexOf('?') + 1)," to "var pos = (src.indexOf('?') + 0)," everything is back on track and fine.

**Comment by aFarkas** [comment]
Hi, thx schepp for hunting down this bug :-).
