### ISSUE TITLE
Audio description

### ISSUE THREAD

**Issue by mkra** [aFarkas/jMediaelement#12]
Is audio description available for jMediaelement or at least planned for a futur release?

**Comment by aFarkas** [comment]
Yes, it is supported through the data-role="textaudiodesc" attribute. Here is an example:

```
<a class="track" href="srtfile.srt" data-enabled="enabled" data-role="textaudiodesc">My audio description</a>
```

If you are using this markup. You won't see anything, but the file is automatically fetched and WAI-ARIA is used to directly output the text to a screenreader.

Note: I'm currently building JME2, which will change a lot. And will also support building audiodescription using the track element or the mediagroup attribute.

First release is planned for december/january, but won't have neither fullscreen, track, playlist nor mediagroup support. Those "extra" features will be added step by step... But it will be very nice.

**Comment by mkra** [comment]
Thanks for the quick answer.
Is it possible to add an audio as audio description? I fear not all Browsers support the textaudiodesc role.

**Comment by aFarkas** [comment]
The data-role="textaudiodesc" is a custom attribute, which tells JME to create a WAI-ARIA liveregion wrapper for the track content. Live region support can be considered as good. IE8+, FF3+ and Safari4+ do support it and Jaws 10+, Windows Eyes 5.5, NVDA etc. do also support it on th AT site.

If you want to connect an audio with a video this is also possible. I have written an unofficial plugin for this. I can get the code on monday, but I can't add a lot of doumentation.

**Comment by mkra** [comment]
I have to support IE6 and IE7 as well, so i'll take a look at your plugin if i get the code.

**Comment by aFarkas** [comment]
https://gist.github.com/1373402
