### ISSUE TITLE
load Shoutcast Stream with jMediaelement

### ISSUE THREAD

**Issue by messaoudi-mounir** [aFarkas/jMediaelement#2]
Hi 
thank your for the plugin,it is very nice.

how i can load url for Shoutcast Stream (http://srv2.streaming-ingenierie.fr:8142/;stream.nsv)
im trying to create radio plugin with playlist.

thanks.

**Comment by aFarkas** [comment]
this was fixed with 1.3, but you ahve to hit play twice, due to the fact, that jwplayer doesn't really support shoutcast streams
