### ISSUE TITLE
'timeline-slider'  does not work with jQ 1.7.1

### ISSUE THREAD

**Issue by elz64** [aFarkas/jMediaelement#22]
Hi,
As the handle  'timeline-slider' are ok with jQ 1.6.4, it does not move anymore during playback with jQ1.7.1

**Comment by aFarkas** [comment]
Hi,

thx for your bug report. I know this bug and I know the solution. I try push the fix tomorrow

cheers
alex

**Comment by elz64** [comment]
Hi, thank you

I'm looking for a solution to manage the following, and I'm not sur the 
API is powerful enough..can you help (I post on jQuery forum and 
Stakoverflow..but nothing happens).

I'm looking for a way to synchronize manuals moves of those 
.timeline-slider .ui-slider-handle (forward/reverse playing position)

(2 media playing simultaneously 1 video + 1 audio for _audio 
description_. If the playing can be synchronize,
example for play (same idea for pause -
Copy code
1. $(document).bind('play',function(e){
   // $('video, audio').not(e.target).pause();
                                $('video, audio').not(e.target).play();
   });

When manipulating one of the handles .ui-slider-handle, it gets the 
ui-state-active too. So it should be possible to know wich one (audio or 
video) is touched and leaved and then managing the other one to reflect 
the time slide (forcing its position using ".currentTime(myvalue)".

I made many tries like this one but it's processed all time, not only 
when moving the handles, so it's a performance issue and I'm sure 
there's a better way...

|$('audio, video').bind('timechange', function(e, data){
newTime = data.time;
dnewTime = newTime - oldTime;// delta T (sec)
oldTime = newTime;
if (( dnewTime>  1) || (dnewTime<  -1)) // handler has been moved widely delta time is big
{
$('video, audio').not(e.target).currentTime(newTime);
};
$('#jmeLog').html('newTime: '+ newTime + ' | dT: ' + dnewTime );
});
|

Thank you
Eric

**Comment by aFarkas** [comment]
Your bug should be fixed with [version 1.3.5final](https://github.com/aFarkas/jMediaelement/tags). 

With your other issue. I'm currently not 100% sure, but do you need something like an audiodescription then you should look into Issue #12).

The following gist might help you https://gist.github.com/1373402.
