### ISSUE TITLE
Howto create vertical volume slider?

### ISSUE THREAD

**Issue by localhorst** [aFarkas/jMediaelement#26]
When calling the jMe API, i can only use this markup:
<code> < div class="volume-slider" title="volume slider" >< / div > </code>

Which will be replaced by a horizontal volume slider. 
How can I adjust the volume handle to be vertical (bottom/silent to top/loud)?

**Comment by localhorst** [comment]
2 month, no feedback - does this mean it is not possible (yet)?

**Comment by aFarkas** [comment]
Sorry, for not answering. I was simply blind. It's quite simple. JME uses jQuery UI slider and jQuery UI automatically detects wether you want a vertical or horizontal slider by your CSS. The only thing you have to do is to give your slider a bigger height than a bigger width.

The following css would create a vertical slider:

```
.volume-slider {
    height: 300px;
    width: 20px;
}
```

If this doesn't help, you can pass a vertical option to the slider. But this should work.

**Comment by localhorst** [comment]
Thanks, sure it works. 
BTW: I mentioned this on Stackoverflow: http://stackoverflow.com/a/13846661/283854
