### ISSUE TITLE
HTML5/MP4 and Flash/FLV

### ISSUE THREAD

**Issue by d3x7ro** [aFarkas/jMediaelement#27]
I have been trying to do HTML5/Flash player. I don't care what falls back to what I just need to make sure HTML5 plays MP4 and Flash plays FLV. HTML5 players use HTTP range requests to do their seeking and flash player uses a 'start' parameter. My webserver can only handle this start parameter on FLV files so its very important the Flash player does not just play the MP4 as the user will not be able to seek.

**Comment by aFarkas** [comment]
I'm not sure, wether I understand you, but the flashfallback takes the first element it can play. So you can force the flashfallback to use the flv version by using it as the first source:

```
<video controls preload="none" poster="poster.jpg" style="width: 630px; height: 356px;">
    <source src="video.flv" type="video/flv" />
    <source src="video.m4v" type="video/mp4" />
    <p>You need a modern Browser or install the Flash Plugin</p>
</video>
```

But honestly, I think you have a different problem. Flashplayer seek and play mp4 progressive. Please see [this article](http://www.adobe.com/devnet/video/articles/mp4_movie_atom.html). You can try the following AIR tool to swap the moov atom index (http://renaun.com/blog/2010/06/qtindexswapper-2/).

Please re-open, if this didn't help.
