### ISSUE TITLE
Poster Plugin for JME

### ISSUE THREAD

**Issue by ghost** [aFarkas/jMediaelement#9]
Hi Alex,

I've put together a poster plugin for JME that I'd like to contribute to the project.  I tried to keep it consistent with the track plugin.  It simply allows the poster image to be redisplayed once the media element has ended.  I couldn't attach the binaries (i.e. video files and poster images I used), git seems like it only accepts text files.  Anyway, here's the link to the files I could attach.  

https://gist.github.com/1215296

Let me know if you have any questions.

Cheers,
Matt

**Comment by ghost** [comment]
Hi Alex,

Just saw Issue 7, I think the poster plugin will actually provide a workaround for that issue.  Seems there's a bug in iOS3 that's been fixed in iOS4. The workaround requires that no poster attribute br assigned to the video element, and instead rely on the src of the fallback image.

HTH,
Matt

**Comment by aFarkas** [comment]
Wow, great work thanks. Can I add your plugin to my plugin folder inside of the jmediaelement repository or should I only add a link to your gist?

cheers
alex

**Comment by ghost** [comment]
You're welcome.  I'm glad you like it. Yes, please add it to your plugin folder.

**Comment by aFarkas** [comment]
I only want to let you know, that I will work next week on this. I don't really have the time to do all things this weekend.
